# Generated by Django 2.1.4 on 2021-09-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CatSlug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PrdSlug',
            new_name='slug',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
